import React, { createContext, useContext, useState, useEffect } from 'react';

// 5 Languages: English, Spanish, Hindi, French, German
export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
];

export const translations = {
  en: {
    nav: {
      brand: 'FindBack AI',
      landing: 'Home',
      dashboard: 'Dashboard',
      my_reports: 'My Reports',
      matches: 'AI Matches',
      notifications: 'Notifications',
      admin: 'Admin Console',
      login: 'Sign In',
      register: 'Get Started',
      logout: 'Sign Out',
      report_lost: 'Report Lost Item',
      report_found: 'Report Found Item',
    },
    hero: {
      badge: 'AI-Powered Enterprise Item Recovery',
      title: 'Reconnect Lost Belongings with Precision AI',
      subtitle: 'FindBack AI utilizes multimodal computer vision, spatial cell indexing, and cryptographic handover verification to return lost items securely.',
      btn_lost: 'I Lost Something',
      btn_found: 'I Found Something',
      stats_recovered: 'Items Recovered',
      stats_accuracy: 'Match Accuracy',
      stats_speed: 'Avg. Return Time',
    },
    dashboard: {
      welcome: 'Welcome Back',
      subtitle: 'Overview of your lost & found reports, active matches, and handover claims.',
      total_reports: 'Active Reports',
      ai_matches: 'AI Matches',
      active_claims: 'Active Claims',
      completed_returns: 'Successful Returns',
      recent_activity: 'Recent Activity',
      no_activity: 'No recent activity recorded.',
    },
    report: {
      title_lost: 'Report a Lost Item',
      title_found: 'Report a Found Item',
      item_name: 'Item Title / Name',
      category: 'Item Category',
      location: 'Last Known Location',
      date: 'Date Lost / Found',
      description: 'Detailed Description',
      upload_image: 'Upload Image / Capture Photo',
      submit_btn: 'Submit Report',
      submitting: 'Submitting...',
    },
    claim: {
      title: 'Submit Ownership Claim',
      evidence_label: 'Ownership Evidence / Proof',
      evidence_help: 'Upload photos, serial numbers, receipts, or unique identifiers proving ownership.',
      submit_claim: 'Submit Claim for Verification',
      status_submitted: 'Under Review',
      status_approved: 'Approved for Handover',
      status_rejected: 'Claim Rejected',
      handover_code: 'Your 6-Digit Handover Verification Code',
    },
    admin: {
      title: 'Enterprise Admin Command Center',
      pending_claims: 'Pending Claims Review',
      system_telemetry: 'System Telemetry & Health',
      btn_approve: 'Approve Claim',
      btn_reject: 'Reject Claim',
      btn_request_more: 'Request Evidence',
    },
    login: {
      title: 'Welcome back',
      subtitle: 'Log in to your account with verified credentials',
      email_label: 'Email address / Username',
      password_label: 'Password',
      forgot_password: 'Forgot password?',
      login_btn: 'Log in',
      logging_in: 'Logging in...',
      no_account: "Don't have an account?",
      create_one: 'Create one',
    },
    register: {
      title: 'Create your account',
      subtitle: 'Register into Supabase database with role-based permissions',
      fullname_label: 'Full Name',
      email_label: 'Email Address',
      phone_label: 'Mobile Phone Number',
      auto_detect_sim: 'Auto-Detect SIM',
      role_label: 'System Role',
      role_citizen: 'Citizen (Item Reporter)',
      permissions_btn: 'Configure Android Permissions (Location, Camera, Notifications)',
      password_label: 'Password',
      confirm_password: 'Confirm Password',
      security_key_label: '6-Character Security Key (Account Recovery)',
      submit_btn: 'Register as Citizen & Launch Portal',
      has_account: 'Already registered in the database?',
      login_here: 'Log in here',
    },
    profile: {
      title: 'User Profile & Settings',
      subtitle: 'Manage your personal profile, security credentials, and preferences',
      account_status: 'Account Status',
      active: 'Active',
      role: 'Assigned Role',
      phone: 'Phone Number',
      security_key: 'Security Recovery Key',
      language_pref: 'Language Preference',
      biometrics: 'Biometric Authentication (Touch ID / Face ID)',
      logout_btn: 'Sign Out of Account',
    },
    smart_tag: {
      title: 'Smart QR Anti-Loss Tag Generator',
      subtitle: 'Attach anti-loss QR smart tags to your laptops, keys, and bags.',
      item_title: 'Item Title / Model / Serial',
      category: 'Category',
      note: 'Finder Relay Note',
      generate_btn: 'Generate Anti-Loss QR Code',
    },
    common: {
      language: 'Language',
      select_language: 'Select Language',
      loading: 'Loading...',
      success: 'Success',
      error: 'An error occurred',
      cancel: 'Cancel',
      confirm: 'Confirm',
      close: 'Close',
      back: 'Back',
      exit: 'Exit',
    },
  },
  es: {
    nav: {
      brand: 'FindBack AI',
      landing: 'Inicio',
      dashboard: 'Panel',
      my_reports: 'Mis Reportes',
      matches: 'Coincidencias IA',
      notifications: 'Notificaciones',
      admin: 'Consola Admin',
      login: 'Iniciar Sesión',
      register: 'Registrarse',
      logout: 'Cerrar Sesión',
      report_lost: 'Reportar Objeto Perdido',
      report_found: 'Reportar Objeto Encontrado',
    },
    hero: {
      badge: 'Recuperación de Objetos impulsada por IA',
      title: 'Reconecta Objetos Perdidos con IA de Precisión',
      subtitle: 'FindBack AI utiliza visión por computadora multimodal e indexación espacial para devolver objetos perdidos de forma segura.',
      btn_lost: 'Perdí Algo',
      btn_found: 'Encontré Algo',
      stats_recovered: 'Objetos Recuperados',
      stats_accuracy: 'Precisión de Coincidencia',
      stats_speed: 'Tiempo Promedio de Devolución',
    },
    dashboard: {
      welcome: 'Bienvenido de nuevo',
      subtitle: 'Resumen de sus reportes, coincidencias activas y reclamaciones de entrega.',
      total_reports: 'Reportes Activos',
      ai_matches: 'Coincidencias IA',
      active_claims: 'Reclamaciones Activas',
      completed_returns: 'Devoluciones Exitosas',
      recent_activity: 'Actividad Reciente',
      no_activity: 'No hay actividad reciente registrada.',
    },
    report: {
      title_lost: 'Reportar un Objeto Perdido',
      title_found: 'Reportar un Objeto Encontrado',
      item_name: 'Título / Nombre del Objeto',
      category: 'Categoría del Objeto',
      location: 'Última Ubicación Conocida',
      date: 'Fecha Perdido / Encontrado',
      description: 'Descripción Detallada',
      upload_image: 'Subir Imagen / Tomar Foto',
      submit_btn: 'Enviar Reporte',
      submitting: 'Enviando...',
    },
    claim: {
      title: 'Presentar Reclamación de Propiedad',
      evidence_label: 'Prueba de Propiedad',
      evidence_help: 'Suba fotos, números de serie o recibos que demuestren su propiedad.',
      submit_claim: 'Enviar Reclamación para Verificación',
      status_submitted: 'En Revisión',
      status_approved: 'Aprobado para Entrega',
      status_rejected: 'Reclamación Rechazada',
      handover_code: 'Su Código de Verificación de Entrega de 6 Dígitos',
    },
    admin: {
      title: 'Centro de Comando de Administración',
      pending_claims: 'Revisión de Reclamaciones Pendientes',
      system_telemetry: 'Telemetría y Salud del Sistema',
      btn_approve: 'Aprobar Reclamación',
      btn_reject: 'Rechazar Reclamación',
      btn_request_more: 'Solicitar Pruebas',
    },
    login: {
      title: 'Bienvenido de nuevo',
      subtitle: 'Inicia sesión con tus credenciales verificadas',
      email_label: 'Correo electrónico / Nombre de usuario',
      password_label: 'Contraseña',
      forgot_password: '¿Olvidaste tu contraseña?',
      login_btn: 'Iniciar sesión',
      logging_in: 'Iniciando sesión...',
      no_account: '¿No tienes una cuenta?',
      create_one: 'Créala',
    },
    register: {
      title: 'Crea tu cuenta',
      subtitle: 'Regístrate en la base de datos con permisos basados en roles',
      fullname_label: 'Nombre completo',
      email_label: 'Dirección de correo electrónico',
      phone_label: 'Número de teléfono móvil',
      auto_detect_sim: 'Auto-detectar SIM',
      role_label: 'Rol del sistema',
      role_citizen: 'Ciudadano (reportador de objetos)',
      permissions_btn: 'Configurar permisos de Android',
      password_label: 'Contraseña',
      confirm_password: 'Confirmar contraseña',
      security_key_label: 'Clave de seguridad de 6 caracteres',
      submit_btn: 'Registrarse como Ciudadano',
      has_account: '¿Ya tienes una cuenta?',
      login_here: 'Inicia sesión aquí',
    },
    profile: {
      title: 'Perfil y Configuración',
      subtitle: 'Gestiona tu perfil personal y preferencias',
      account_status: 'Estado de la cuenta',
      active: 'Activo',
      role: 'Rol asignado',
      phone: 'Número de teléfono',
      security_key: 'Clave de recuperación',
      language_pref: 'Preferencia de idioma',
      biometrics: 'Autenticación biométrica',
      logout_btn: 'Cerrar sesión',
    },
    common: {
      language: 'Idioma',
      select_language: 'Seleccionar Idioma',
      loading: 'Cargando...',
      success: 'Éxito',
      error: 'Ocurrió un error',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      close: 'Cerrar',
    },
  },
  hi: {
    nav: {
      brand: 'FindBack AI',
      landing: 'मुख्य पृष्ठ',
      dashboard: 'डैशबोर्ड',
      my_reports: 'मेरी रिपोर्ट',
      matches: 'एआई मिलान',
      notifications: 'सूचनाएं',
      admin: 'एडमिन कंसोल',
      login: 'साइन इन करें',
      register: 'शुरू करें',
      logout: 'साइन आउट',
      report_lost: 'खोया सामान दर्ज करें',
      report_found: 'पाया सामान दर्ज करें',
    },
    hero: {
      badge: 'एआई-संचालित खोया-पाया रिकवरी प्लेटफॉर्म',
      title: 'खोई हुई वस्तुओं को सटीक एआई तकनीक से वापस पाएं',
      subtitle: 'FindBack AI कंप्यूटर विज़न और लोकेशन ट्रैकिंग का उपयोग करके आपकी खोई हुई वस्तुओं को सुरक्षित रूप से वापस लाता है।',
      btn_lost: 'मेरा सामान खो गया',
      btn_found: 'मुझे सामान मिला',
      stats_recovered: 'बरामद वस्तुएं',
      stats_accuracy: 'सटीकता दर',
      stats_speed: 'औसत वापसी समय',
    },
    dashboard: {
      welcome: 'पुनः स्वागत है',
      subtitle: 'आपकी खोई-पायी रिपोर्ट, सक्रिय एआई मैचों और दावों का अवलोकन।',
      total_reports: 'सक्रिय रिपोर्ट',
      ai_matches: 'एआई मैच',
      active_claims: 'सक्रिय दावे',
      completed_returns: 'सफल वापसी',
      recent_activity: 'हाल की गतिविधि',
      no_activity: 'कोई हालिया गतिविधि नहीं।',
    },
    report: {
      title_lost: 'खोई हुई वस्तु की रिपोर्ट करें',
      title_found: 'मिली हुई वस्तु की रिपोर्ट करें',
      item_name: 'वस्तु का नाम',
      category: 'वस्तु श्रेणी',
      location: 'अंतिम ज्ञात स्थान',
      date: 'तारीख',
      description: 'विस्तृत विवरण',
      upload_image: 'फोटो अपलोड करें / खींचें',
      submit_btn: 'रिपोर्ट जमा करें',
      submitting: 'जमा हो रहा है...',
    },
    claim: {
      title: 'स्वामित्व का दावा प्रस्तुत करें',
      evidence_label: 'स्वामित्व का प्रमाण',
      evidence_help: 'रसीद, सीरियल नंबर या फोटो अपलोड करें जो स्वामित्व साबित करे।',
      submit_claim: 'सत्यापन के लिए दावा भेजें',
      status_submitted: 'समीक्षा के अधीन',
      status_approved: 'हैंडओवर के लिए स्वीकृत',
      status_rejected: 'दावा खारिज',
      handover_code: 'आपका 6-अंकों का हैंडओवर कोड',
    },
    admin: {
      title: 'एडमिन कमांड सेंटर',
      pending_claims: 'लंबित दावों की समीक्षा',
      system_telemetry: 'सिस्टम टेलीमेट्री और स्वास्थ्य',
      btn_approve: 'दावा स्वीकृत करें',
      btn_reject: 'दावा अस्वीकृत करें',
      btn_request_more: 'अधिक साक्ष्य मांगें',
    },
    login: {
      title: 'पुनः स्वागत है',
      subtitle: 'सत्यापित क्रेडेंशियल के साथ अपने खाते में लॉग इन करें',
      email_label: 'ईमेल पता / उपयोगकर्ता नाम',
      password_label: 'पासवर्ड',
      forgot_password: 'पासवर्ड भूल गए?',
      login_btn: 'लॉग इन करें',
      logging_in: 'लॉग इन हो रहा है...',
      no_account: 'कोई खाता नहीं है?',
      create_one: 'बनाएं',
    },
    register: {
      title: 'अपना खाता बनाएं',
      subtitle: 'भूमिका-आधारित अनुमतियों के साथ डेटाबेस में पंजीकरण करें',
      fullname_label: 'पूरा नाम',
      email_label: 'ईमेल पता',
      phone_label: 'मोबाइल फोन नंबर',
      auto_detect_sim: 'SIM ऑटो-डिटेक्ट',
      role_label: 'सिस्टम भूमिका',
      role_citizen: 'नागरिक (आइटम रिपोर्टर)',
      permissions_btn: 'Android अनुमतियां कॉन्फ़िगर करें',
      password_label: 'पासवर्ड',
      confirm_password: 'पासवर्ड की पुष्टि करें',
      security_key_label: '6-कैरेक्टर सुरक्षा कुंजी',
      submit_btn: 'नागरिक के रूप में पंजीकरण करें',
      has_account: 'पहले से पंजीकृत हैं?',
      login_here: 'यहां लॉग इन करें',
    },
    profile: {
      title: 'उपयोगकर्ता प्रोफ़ाइल और सेटिंग्स',
      subtitle: 'अपनी प्रोफ़ाइल और प्राथमिकताएं प्रबंधित करें',
      account_status: 'खाता स्थिति',
      active: 'सक्रिय',
      role: 'नियुक्त भूमिका',
      phone: 'फोन नंबर',
      security_key: 'सुरक्षा पुनर्प्राप्ति कुंजी',
      language_pref: 'भाषा प्राथमिकता',
      biometrics: 'बायोमेट्रिक प्रमाणीकरण',
      logout_btn: 'खाते से साइन आउट करें',
    },
    common: {
      language: 'भाषा',
      select_language: 'भाषा चुनें',
      loading: 'लोड हो रहा है...',
      success: 'सफलता',
      error: 'एक त्रुटि हुई',
      cancel: 'रद्द करें',
      confirm: 'पुष्टि करें',
      close: 'बंद करें',
    },
  },
  fr: {
    nav: {
      brand: 'FindBack AI',
      landing: 'Accueil',
      dashboard: 'Tableau de bord',
      my_reports: 'Mes Signalements',
      matches: 'Correspondances IA',
      notifications: 'Notifications',
      admin: 'Console Admin',
      login: 'Se Connecter',
      register: 'S’inscrire',
      logout: 'Se Déconnecter',
      report_lost: 'Signaler un Objet Perdu',
      report_found: 'Signaler un Objet Trouvé',
    },
    hero: {
      badge: 'Récupération d’objets propulsée par l’IA',
      title: 'Retrouvez vos objets perdus grâce à l’IA de précision',
      subtitle: 'FindBack AI utilise la vision par ordinateur et l’indexation spatiale pour restituer vos objets perdus en toute sécurité.',
      btn_lost: 'J’ai Perdu Quelque Chose',
      btn_found: 'J’ai Trouvé Quelque Chose',
      stats_recovered: 'Objets Restitués',
      stats_accuracy: 'Précision du Match',
      stats_speed: 'Temps Moyen de Restitution',
    },
    dashboard: {
      welcome: 'Bon retour parmis nous',
      subtitle: 'Vue d’ensemble de vos signalements, correspondances actives et réclamations.',
      total_reports: 'Signalements Actifs',
      ai_matches: 'Matches IA',
      active_claims: 'Réclamations Actives',
      completed_returns: 'Restitutions Réussies',
      recent_activity: 'Activité Récente',
      no_activity: 'Aucune activité récente enregistrée.',
    },
    report: {
      title_lost: 'Signaler un Objet Perdu',
      title_found: 'Signaler un Objet Trouvé',
      item_name: 'Nom / Titre de l’Objet',
      category: 'Catégorie d’Objet',
      location: 'Dernier Emplacement Connu',
      date: 'Date Perdu / Trouvé',
      description: 'Description Détaillée',
      upload_image: 'Téléverser / Prendre une Photo',
      submit_btn: 'Soumettre le Signalement',
      submitting: 'Envoi en cours...',
    },
    claim: {
      title: 'Soumettre une Réclamation de Propriété',
      evidence_label: 'Preuve de Propriété',
      evidence_help: 'Téléversez des photos, factures ou numéros de série prouvant votre propriété.',
      submit_claim: 'Soumettre la Réclamation',
      status_submitted: 'En Cours d’Examen',
      status_approved: 'Approuvé pour Remise',
      status_rejected: 'Réclamation Rejetée',
      handover_code: 'Votre Code de Vérification à 6 Chiffres',
    },
    admin: {
      title: 'Centre de Commande Administration',
      pending_claims: 'Réclamations en Attente',
      system_telemetry: 'Télémétrie et Santé Système',
      btn_approve: 'Approuver',
      btn_reject: 'Rejeter',
      btn_request_more: 'Demander des Preuves',
    },
    login: {
      title: 'Bon retour',
      subtitle: 'Connectez-vous avec des identifiants vérifiés',
      email_label: "Adresse e-mail / Nom d'utilisateur",
      password_label: 'Mot de passe',
      forgot_password: 'Mot de passe oublié?',
      login_btn: 'Se connecter',
      logging_in: 'Connexion en cours...',
      no_account: 'Pas de compte?',
      create_one: 'En créer un',
    },
    register: {
      title: 'Créer votre compte',
      subtitle: 'Inscrivez-vous dans la base de données avec des permissions basées sur les rôles',
      fullname_label: 'Nom complet',
      email_label: 'Adresse e-mail',
      phone_label: 'Numéro de téléphone mobile',
      auto_detect_sim: 'Auto-détecter la SIM',
      role_label: 'Rôle système',
      role_citizen: "Citoyen (Déclarant d'objet)",
      permissions_btn: 'Configurer les permissions Android',
      password_label: 'Mot de passe',
      confirm_password: 'Confirmer le mot de passe',
      security_key_label: 'Clé de sécurité 6 caractères',
      submit_btn: "S'inscrire en tant que Citoyen",
      has_account: 'Déjà inscrit?',
      login_here: 'Se connecter ici',
    },
    profile: {
      title: 'Profil et Paramètres',
      subtitle: 'Gérez votre profil personnel et vos préférences',
      account_status: 'Statut du compte',
      active: 'Actif',
      role: 'Rôle attribué',
      phone: 'Numéro de téléphone',
      security_key: 'Clé de récupération',
      language_pref: 'Préférence de langue',
      biometrics: 'Authentification biométrique',
      logout_btn: 'Se déconnecter du compte',
    },
    common: {
      language: 'Langue',
      select_language: 'Choisir la Langue',
      loading: 'Chargement...',
      success: 'Succès',
      error: "Une erreur s'est produite",
      cancel: 'Annuler',
      confirm: 'Confirmer',
      close: 'Fermer',
    },
  },
  de: {
    nav: {
      brand: 'FindBack AI',
      landing: 'Startseite',
      dashboard: 'Dashboard',
      my_reports: 'Meine Meldungen',
      matches: 'KI-Treffer',
      notifications: 'Benachrichtigungen',
      admin: 'Admin-Konsole',
      login: 'Anmelden',
      register: 'Registrieren',
      logout: 'Abmelden',
      report_lost: 'Verlust Melden',
      report_found: 'Fund Melden',
    },
    hero: {
      badge: 'KI-Gestützte Fundbüro-Plattform',
      title: 'Verlorene Gegenstände mit Präzisions-KI wiederfinden',
      subtitle: 'FindBack AI nutzt Bilderkennung und Standort-Indexierung, um verloren gegangene Gegenstände sicher zurückzugeben.',
      btn_lost: 'Ich habe etwas verloren',
      btn_found: 'Ich habe etwas gefunden',
      stats_recovered: 'Wiedergefundene Objekte',
      stats_accuracy: 'Trefferquote',
      stats_speed: 'Avg. Rückgabezeit',
    },
    dashboard: {
      welcome: 'Willkommen zurück',
      subtitle: 'Übersicht Ihrer Fund- und Verlustmeldungen sowie aktiven KI-Treffer.',
      total_reports: 'Aktive Meldungen',
      ai_matches: 'KI-Treffer',
      active_claims: 'Aktive Ansprüche',
      completed_returns: 'Erfolgreiche Rückgaben',
      recent_activity: 'Letzte Aktivitäten',
      no_activity: 'Keine letzten Aktivitäten vorhanden.',
    },
    report: {
      title_lost: 'Verlorenen Gegenstand melden',
      title_found: 'Gefundenen Gegenstand melden',
      item_name: 'Bezeichnung / Name',
      category: 'Kategorie',
      location: 'Letzter bekannter Ort',
      date: 'Datum',
      description: 'Detaillierte Beschreibung',
      upload_image: 'Foto hochladen / aufnehmen',
      submit_btn: 'Meldung Absenden',
      submitting: 'Wird gesendet...',
    },
    claim: {
      title: 'Eigentumsanspruch Einreichen',
      evidence_label: 'Eigentumsnachweis',
      evidence_help: 'Laden Sie Fotos, Seriennummern oder Kaufbelege hoch, die Ihren Anspruch belegen.',
      submit_claim: 'Anspruch zur Prüfung Absenden',
      status_submitted: 'In Prüfung',
      status_approved: 'Zur Übergabe Freigegeben',
      status_rejected: 'Anspruch Abgelehnt',
      handover_code: 'Ihr 6-stelliger Übergabe-Bestätigungscode',
    },
    admin: {
      title: 'Admin-Kommandozentrale',
      pending_claims: 'Offene Ansprüche Prüfen',
      system_telemetry: 'System-Telemetrie & Zustand',
      btn_approve: 'Anspruch Genehmigen',
      btn_reject: 'Anspruch Ablehnen',
      btn_request_more: 'Nachweise Anfordern',
    },
    login: {
      title: 'Willkommen zurück',
      subtitle: 'Melden Sie sich mit verifizierten Anmeldedaten an',
      email_label: 'E-Mail-Adresse / Benutzername',
      password_label: 'Passwort',
      forgot_password: 'Passwort vergessen?',
      login_btn: 'Anmelden',
      logging_in: 'Anmeldung läuft...',
      no_account: 'Kein Konto?',
      create_one: 'Erstellen',
    },
    register: {
      title: 'Konto erstellen',
      subtitle: 'Registrieren Sie sich in der Datenbank mit rollenbasierten Berechtigungen',
      fullname_label: 'Vollständiger Name',
      email_label: 'E-Mail-Adresse',
      phone_label: 'Handynummer',
      auto_detect_sim: 'SIM automatisch erkennen',
      role_label: 'Systemrolle',
      role_citizen: 'Bürger (Gegenstand-Melder)',
      permissions_btn: 'Android-Berechtigungen konfigurieren',
      password_label: 'Passwort',
      confirm_password: 'Passwort bestätigen',
      security_key_label: '6-stelliger Sicherheitsschlüssel',
      submit_btn: 'Als Bürger registrieren',
      has_account: 'Bereits registriert?',
      login_here: 'Hier anmelden',
    },
    profile: {
      title: 'Benutzerprofil & Einstellungen',
      subtitle: 'Verwalten Sie Ihr Profil und Ihre Einstellungen',
      account_status: 'Kontostatus',
      active: 'Aktiv',
      role: 'Zugewiesene Rolle',
      phone: 'Telefonnummer',
      security_key: 'Sicherheitswiederherstellungsschlüssel',
      language_pref: 'Sprachpräferenz',
      biometrics: 'Biometrische Authentifizierung',
      logout_btn: 'Vom Konto abmelden',
    },
    common: {
      language: 'Sprache',
      select_language: 'Sprache Auswählen',
      loading: 'Laden...',
      success: 'Erfolg',
      error: 'Ein Fehler ist aufgetreten',
      cancel: 'Abbrechen',
      confirm: 'Bestätigen',
      close: 'Schließen',
    },
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('findback_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('findback_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (path) => {
    const keys = path.split('.');
    let current = translations[language] || translations.en;
    for (const key of keys) {
      if (current && current[key] !== undefined) {
        current = current[key];
      } else {
        // Fallback to English if key missing in selected language
        let fallback = translations.en;
        for (const fk of keys) {
          if (fallback && fallback[fk] !== undefined) {
            fallback = fallback[fk];
          } else {
            return path;
          }
        }
        return fallback;
      }
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export const useTranslation = () => {
  const { t, language, setLanguage, languages } = useLanguage();
  return { t, language, setLanguage, languages };
};

export default LanguageContext;
